// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4K_JM5ahg-jvie3sJMowp_Ss0Mw3tvk',
    appId: '1:643156710561:web:be462e8f7a94f2c8e40ce0',
    messagingSenderId: '643156710561',
    projectId: 'flutterapp-project',
    authDomain: 'flutterapp-project.firebaseapp.com',
    storageBucket: 'flutterapp-project.appspot.com',
    measurementId: 'G-R9XDCKZL9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2VWqysn0IVqUZ-UlicqjiTdzOCLMg0o',
    appId: '1:643156710561:android:40c42cf8dd56910be40ce0',
    messagingSenderId: '643156710561',
    projectId: 'flutterapp-project',
    storageBucket: 'flutterapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfZa7CU4_6oLeXKvnrbVNAwD_L98hNuo',
    appId: '1:643156710561:ios:053cb498ec9bdb51e40ce0',
    messagingSenderId: '643156710561',
    projectId: 'flutterapp-project',
    storageBucket: 'flutterapp-project.appspot.com',
    iosClientId: '643156710561-qqnd1hnijea43a5f2tufks59lar5v6ud.apps.googleusercontent.com',
    iosBundleId: 'tech.fionawekulo.flutterapp',
  );
}
